Repository DailyBotHQ/universal-emoji-parser, pull requests merged in 2023-07, with the labels that each got.

#168 Improving automations to allow add Size label to the PRs
  .github/workflows/pull_request_check.yml
Labels: Size - M

#170 Improving workflows checks
  .github/workflows/pull_request_check.yml
  .github/workflows/release_and_publish.yml
Labels: Size - S

#171 PR labels Check
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#172 PR labels Check
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#173 Updating workflows
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#174 PR labels Check
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#175 PR labels Check
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#176 PR labels Check
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#178 PR labels Check
  .github/workflows/release_and_publish.yml
Labels: Size - XS

#180 PR labels Check
  .github/workflows/pull_request_check.yml
Labels: Size - XS

#181 Improving workflows
  .github/workflows/pull_request_check.yml
  .github/workflows/release_and_publish.yml
Labels: Size - S

#182 Adding check branches state workflow
  .github/workflows/check_branches_state.yml
Labels: Size - XS

#184 Adding workflow to check the state of branches
  .github/workflows/check_and_merge_packages_upgrades_pr.yml
  .github/workflows/check_branches_state.yml
  .github/workflows/check_packages_versions.yml
  .github/workflows/release_and_publish.yml
  =
  script.sh
Labels: Size - S

#185 Improving workflows
  .github/workflows/check_branches_state.yml
  .github/workflows/pull_request_check.yml
  script.sh
Labels: Size - XS

#186 🤖 Upgrading packages versions
  package-lock.json
  package.json
Labels: Size - M

#187 Updating notification channels vars
  .github/workflows/check_and_merge_packages_upgrades_pr.yml
  .github/workflows/check_branches_state.yml
  .github/workflows/check_packages_versions.yml
  .github/workflows/release_and_publish.yml
Labels: Size - XS
